name: Update JSON File

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install axios

      - name: Run update-json script
        run: node update-json.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Pastikan GH_TOKEN dipanggil dengan benar
